#!/bin/bash
# Lance Liquidsoap avec les arguments passés
which liquidsoap
liquidsoap --version

ENV ICECAST_HOSTNAME=${ICECAST_HOSTNAME//\"/}
ENV ICECAST_PORT=8000
ENV ICECAST_PASSWORD=${ICECAST_PASSWORD//\"/}
ENV ICECAST_MOUNTPOINT=${ICECAST_MOUNTPOINT//\"/}
ENV ICECAST_BITRATE=320

ENV ICECAST_RADIO_NAME=${ICECAST_RADIO_NAME//\"/}
ENV ICECAST_RADIO_DESCRIPTION=${ICECAST_RADIO_DESCRIPTION//\"/}
ENV ICECAST_RADIO_URL="http://$ICECAST_HOSTNAME:$ICECAST_PORT$ICECAST_MOUNTPOINT"
ENV ICECAST_RADIO_GENDER=${ICECAST_RADIO_GENDER//\"/}
ENV ICECAST_RADIO_PUBLIC=true



envsubst < /app/radio.liq.template > radio.liq

cat /app/radio.liq
liquidsoap "$@"
